import GettingStarted from "@/components/GettingStarted";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <main className="">
      <Head>
        <title>My Notes - Welcome !</title>
        <meta
          name="description"
          content={"Notes" || "Generated by create next app"}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <GettingStarted />
      </div>
    </main>
  );
}
